"""empty message

Revision ID: 0924ae49c2cc
Revises: dce88867c08b
Create Date: 2025-05-28 11:56:25.034659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0924ae49c2cc'
down_revision = 'dce88867c08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('title3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion3', sa.String(length=500), nullable=True))

    with op.batch_alter_table('gastronomia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('title3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion3', sa.String(length=500), nullable=True))

    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('title3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion3', sa.String(length=500), nullable=True))

    with op.batch_alter_table('top', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('title3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion3', sa.String(length=500), nullable=True))

    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('title3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion3', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('descripcion3')
        batch_op.drop_column('title3')
        batch_op.drop_column('descripcion2')
        batch_op.drop_column('title2')
        batch_op.drop_column('image5')
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')

    with op.batch_alter_table('top', schema=None) as batch_op:
        batch_op.drop_column('descripcion3')
        batch_op.drop_column('title3')
        batch_op.drop_column('descripcion2')
        batch_op.drop_column('title2')
        batch_op.drop_column('image5')
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')

    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.drop_column('descripcion3')
        batch_op.drop_column('title3')
        batch_op.drop_column('descripcion2')
        batch_op.drop_column('title2')
        batch_op.drop_column('image5')
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')

    with op.batch_alter_table('gastronomia', schema=None) as batch_op:
        batch_op.drop_column('descripcion3')
        batch_op.drop_column('title3')
        batch_op.drop_column('descripcion2')
        batch_op.drop_column('title2')
        batch_op.drop_column('image5')
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')

    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.drop_column('descripcion3')
        batch_op.drop_column('title3')
        batch_op.drop_column('descripcion2')
        batch_op.drop_column('title2')
        batch_op.drop_column('image5')
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')

    # ### end Alembic commands ###
