"""empty message

Revision ID: 09599229e589
Revises: 6f0bf8277c4c
Create Date: 2025-04-25 05:28:16.846381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09599229e589'
down_revision = '6f0bf8277c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('politicas')
    # ### end Alembic commands ###
