"""empty message

Revision ID: 0bef2bf404af
Revises: 0550ed4457d3
Create Date: 2025-05-08 03:01:20.613170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bef2bf404af'
down_revision = '0550ed4457d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('payment_items_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['servicio_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_items_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('servicio_id')

    # ### end Alembic commands ###
