"""empty message

Revision ID: 17720fd5cafe
Revises: ce37ddab5ccd
Create Date: 2025-04-30 05:36:34.476614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17720fd5cafe'
down_revision = 'ce37ddab5ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_viaje', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('category_viaje')

    # ### end Alembic commands ###
