"""empty message

Revision ID: 19c2a5c7e04b
Revises: f80abaf5884f
Create Date: 2025-06-02 12:42:03.875418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c2a5c7e04b'
down_revision = 'f80abaf5884f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=900),
               type_=sa.String(length=1200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=900),
               existing_nullable=True)

    # ### end Alembic commands ###
