"""empty message

Revision ID: 221fc32262e5
Revises: b377f5b9aa61
Create Date: 2025-05-08 04:19:33.830165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221fc32262e5'
down_revision = 'b377f5b9aa61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['servicio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('servicio_id')

    # ### end Alembic commands ###
