"""empty message

Revision ID: 28753ac65c10
Revises: 76dd7da34f25
Create Date: 2025-04-24 13:14:41.015764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28753ac65c10'
down_revision = '76dd7da34f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
