"""empty message

Revision ID: 2d79be3b822d
Revises: b27bf21f9783
Create Date: 2025-04-24 03:24:23.839976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d79be3b822d'
down_revision = 'b27bf21f9783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('discountPrice',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nombre')
        batch_op.drop_column('horarios')
        batch_op.drop_column('originalPrice')
        batch_op.drop_column('precio')
        batch_op.drop_column('ubicacion')

    with op.batch_alter_table('gastronomia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('discountPrice',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nombre')
        batch_op.drop_column('horarios')
        batch_op.drop_column('originalPrice')
        batch_op.drop_column('precio')
        batch_op.drop_column('ubicacion')

    with op.batch_alter_table('top', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('discountPrice',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nombre')
        batch_op.drop_column('horarios')
        batch_op.drop_column('originalPrice')
        batch_op.drop_column('precio')
        batch_op.drop_column('ubicacion')

    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('discountPrice',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('nombre')
        batch_op.drop_column('horarios')
        batch_op.drop_column('originalPrice')
        batch_op.drop_column('precio')
        batch_op.drop_column('ubicacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('originalPrice', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('horarios', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=240), autoincrement=False, nullable=False))
        batch_op.alter_column('discountPrice',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=240),
               existing_nullable=True)
        batch_op.drop_column('price')

    with op.batch_alter_table('top', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('originalPrice', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('horarios', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=240), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('discountPrice',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=240),
               existing_nullable=True)
        batch_op.drop_column('price')
        batch_op.drop_column('description')

    with op.batch_alter_table('gastronomia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('originalPrice', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('horarios', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=240), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('discountPrice',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=240),
               existing_nullable=True)
        batch_op.drop_column('price')
        batch_op.drop_column('description')

    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('originalPrice', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('horarios', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=240), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('discountPrice',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=240),
               existing_nullable=True)
        batch_op.drop_column('price')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
