"""empty message

Revision ID: 3fef8f6440b0
Revises: 3c1475440af5
Create Date: 2025-05-07 23:39:08.083022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fef8f6440b0'
down_revision = '3c1475440af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletterservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_constraint('newsletter_correo_key', type_='unique')
        batch_op.drop_column('correo')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_subscription', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('newsletter_subscription')

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('newsletter_correo_key', ['correo'])

    op.drop_table('newsletterservices')
    # ### end Alembic commands ###
