"""empty message

Revision ID: 43a52e39bd14
Revises: 17720fd5cafe
Create Date: 2025-04-30 06:30:53.673443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a52e39bd14'
down_revision = '17720fd5cafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('category_viaje')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_viaje', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
