"""empty message

Revision ID: 52d99198c48f
Revises: 09599229e589
Create Date: 2025-04-25 18:00:33.805808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d99198c48f'
down_revision = '09599229e589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('servicio', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturas')
    # ### end Alembic commands ###
