"""empty message

Revision ID: 6cc051ebbc23
Revises: 83e354b0b48a
Create Date: 2025-04-22 08:28:17.038647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc051ebbc23'
down_revision = '83e354b0b48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_line1', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('direccion_line2', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('codigo_postal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=50), nullable=True))
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('pais')
        batch_op.drop_column('codigo_postal')
        batch_op.drop_column('ciudad')
        batch_op.drop_column('direccion_line2')
        batch_op.drop_column('direccion_line1')

    # ### end Alembic commands ###
