"""empty message

Revision ID: 823fca081b47
Revises: 58a993ab2cae
Create Date: 2025-04-24 01:13:57.360476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823fca081b47'
down_revision = '58a993ab2cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=240), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
