"""empty message

Revision ID: 83e354b0b48a
Revises: 2de4d84d88e2
Create Date: 2025-04-22 07:29:47.189787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e354b0b48a'
down_revision = '2de4d84d88e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
