"""empty message

Revision ID: b01117a1838b
Revises: d70a463347b4
Create Date: 2025-05-12 17:17:20.238721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01117a1838b'
down_revision = 'd70a463347b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newslettersubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('asunto', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('enviado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('newsletter_subscription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_subscription', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_column('enviado')
        batch_op.drop_column('asunto')
        batch_op.drop_column('titulo')

    op.drop_table('newslettersubscription')
    # ### end Alembic commands ###
