"""empty message

Revision ID: b27bf21f9783
Revises: 823fca081b47
Create Date: 2025-04-24 01:51:52.633509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27bf21f9783'
down_revision = '823fca081b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=240), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discountPrice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('originalPrice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyers', sa.Integer(), nullable=True))

    with op.batch_alter_table('gastronomia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=240), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discountPrice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('originalPrice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyers', sa.Integer(), nullable=True))

    with op.batch_alter_table('top', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=240), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discountPrice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('originalPrice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyers', sa.Integer(), nullable=True))

    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discountPrice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('originalPrice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyers', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('buyers')
        batch_op.drop_column('reviews')
        batch_op.drop_column('rating')
        batch_op.drop_column('originalPrice')
        batch_op.drop_column('discountPrice')
        batch_op.drop_column('city')
        batch_op.drop_column('image')

    with op.batch_alter_table('top', schema=None) as batch_op:
        batch_op.drop_column('buyers')
        batch_op.drop_column('reviews')
        batch_op.drop_column('rating')
        batch_op.drop_column('originalPrice')
        batch_op.drop_column('discountPrice')
        batch_op.drop_column('city')
        batch_op.drop_column('image')
        batch_op.drop_column('title')

    with op.batch_alter_table('gastronomia', schema=None) as batch_op:
        batch_op.drop_column('buyers')
        batch_op.drop_column('reviews')
        batch_op.drop_column('rating')
        batch_op.drop_column('originalPrice')
        batch_op.drop_column('discountPrice')
        batch_op.drop_column('city')
        batch_op.drop_column('image')
        batch_op.drop_column('title')

    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.drop_column('buyers')
        batch_op.drop_column('reviews')
        batch_op.drop_column('rating')
        batch_op.drop_column('originalPrice')
        batch_op.drop_column('discountPrice')
        batch_op.drop_column('city')
        batch_op.drop_column('image')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
