"""empty message

Revision ID: b377f5b9aa61
Revises: 0bef2bf404af
Create Date: 2025-05-08 03:40:49.170202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b377f5b9aa61'
down_revision = '0bef2bf404af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_constraint('payment_items_servicio_id_fkey', type_='foreignkey')
        batch_op.drop_column('servicio_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('payment_items_servicio_id_fkey', 'users', ['servicio_id'], ['id'])

    # ### end Alembic commands ###
