"""empty message

Revision ID: c6c1f8056d93
Revises: 2e0bfd305845
Create Date: 2025-04-24 04:03:34.823108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c1f8056d93'
down_revision = '2e0bfd305845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=500), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('gastronomia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=500), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('top', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=500), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('gastronomia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
