"""empty message

Revision ID: e1af75b9cd5e
Revises: 43a52e39bd14
Create Date: 2025-04-30 06:56:14.178957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1af75b9cd5e'
down_revision = '43a52e39bd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('servicio_id')

    # ### end Alembic commands ###
