"""empty message

Revision ID: f141d6fda8a8
Revises: 19c2a5c7e04b
Create Date: 2025-06-04 12:53:07.065043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f141d6fda8a8'
down_revision = '19c2a5c7e04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=1200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('descripcion2',
               existing_type=sa.VARCHAR(length=900),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('descripcion3',
               existing_type=sa.VARCHAR(length=900),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.alter_column('descripcion3',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=900),
               existing_nullable=True)
        batch_op.alter_column('descripcion2',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=900),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1200),
               existing_nullable=True)

    # ### end Alembic commands ###
