"""empty message

Revision ID: f80abaf5884f
Revises: 0924ae49c2cc
Create Date: 2025-05-30 13:04:07.159712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80abaf5884f'
down_revision = '0924ae49c2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=900),
               existing_nullable=True)
        batch_op.alter_column('descripcion2',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=900),
               existing_nullable=True)
        batch_op.alter_column('descripcion3',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=900),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('belleza', schema=None) as batch_op:
        batch_op.alter_column('descripcion3',
               existing_type=sa.String(length=900),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('descripcion2',
               existing_type=sa.String(length=900),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=900),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
